export const Literal = {
  es: {
    PLEASE_ENTER_VALUE: 'Este campo no puede estar en blanco',
    VALUE_DO_NOT_MATCH: 'Introduzca un valor válido',
    VALUE_MIN: 'No se pueden introducir menos caracteres de ',
    VALUE_MAX: 'No se pueden introducir mas caracteres de ',
    VALUE_EMAIL: 'Se requiere un texto con formato e-mail (test@test.es)',
    VALUE_CHECKED: 'Debe seleccionar esta casilla para completar el formulario',
    CHECK_PASSWORD: 'Las constraseñas no son coincidentes',
    MIN_NUMBER: 'El valor no puede ser inferior a ',
    MAX_NUMBER: 'El valor no puede ser superior a ',
    NO_MATCH_PASSWORD: 'No coincide las contraseñas',
    ACCEPT: 'Aceptar',
    MORE_INFO: 'Mas Información',
    NO_SELECTED_TYPE_DOCUMENT: 'No se ha seleccionado el tipo de documento',
    DOCUMENT_INCORRECT: 'Los datos introducidos no coinciden con un ',
    CIF: 'Cif',
    NIE: 'Nie',
    PASSPORT: 'Pasaporte',
    DNI: 'Dni',
    SELECT_FILE: 'Seleccione un archivo',
    UPLOAD_MAX_FILES: 'No esta permitido subir mas de ',
    FILES_LITERAL: ' ficheros',
    FILES_STRONG_ERROR: 'Los ficheros subidos son demasiado/s grande/s',
    USER_PASS_INCORRECT: 'Usuario o contraseña incorrecta',
  },

  en: {
    PLEASE_ENTER_VALUE: 'This field can not be blank',
    VALUE_DO_NOT_MATCH: 'Enter a valid value',
    VALUE_MIN: 'You cannot enter fewer characters of ',
    VALUE_MAX: 'You cannot enter more characters of ',
    VALUE_EMAIL: 'A text with e-mail format is required (test@test.es)',
    VALUE_CHECKED: 'You must select this box to complete the form',
    CHECK_PASSWORD: 'The passwords are not coincident',
    MIN_NUMBER: 'The value cannot be less than ',
    MAX_NUMBER: 'The value cannot exceed ',
    NO_MATCH_PASSWORD: 'Passwords do not match',
    ACCEPT: 'Accept',
    MORE_INFO: 'More Information',
    NO_SELECTED_TYPE_DOCUMENT: 'The type of document is no selected',
    DOCUMENT_INCORRECT: 'The data insert no match with a ',
    CIF: 'Cif',
    NIE: 'Nie',
    PASSPORT: 'Passport',
    DNI: 'Dni',
    SELECT_FILE: 'Select a file',
    UPLOAD_MAX_FILES: 'It is not allowed to upload more than ',
    FILES_LITERAL: ' files',
    FILES_STRONG_ERROR: 'The uploaded files are too big',
    USER_PASS_INCORRECT: 'Incorrect user or password',
  },
};
